// <auto-generated />
namespace TennisOrganizer.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Trainers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Trainers));
        
        string IMigrationMetadata.Id
        {
            get { return "201501221301405_Trainers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
